"""Offline evaluation of the parser and the scheduler on screenplays the demo never uses. Writes docs/evaluation.md.

    python -m fp.evaluate          # about two minutes: eight time-limited solves
"""
import datetime
import pathlib
import random

from . import engine as e
from . import world

SEEDS = (300, 301, 302, 303)
START = datetime.date(2026, 11, 2)


def main():
    p = {"scenes": 0, "cast": 0, "naive": 0, "heading": 0, "pages": 0}
    rows = []
    dates = e.shoot_dates(START, 30)             # thirty possible days: script order needs the room
    for seed in SEEDS:
        text, truth = world.screenplay(seed)
        scenes, _, _ = e.parse(text)
        for s, n, x in zip(scenes, e.parse_naive(text), truth):
            p["scenes"] += 1
            p["cast"] += s["cast"] == sorted(x["cast"])
            p["naive"] += n == sorted(x["cast"])
            p["heading"] += (s["int_ext"], s["location"], s["time"]) == (x["int_ext"], x["location"], x["time"])
            p["pages"] += s["eighths"] == x["eighths"]
        base = e.script_order(scenes, dates, {})
        plan, status, bound = e.schedule(scenes, dates, world.RATES, world.FEES, {}, {}, hint=base, seconds=12)
        assert not e.violations(scenes, plan, dates, {}) and not e.violations(scenes, base, dates, {})
        a, b = e.cost(scenes, plan, dates, world.RATES, world.FEES, {}), e.cost(scenes, base, dates, world.RATES, world.FEES, {})
        # the same disruption as the demo: the busiest performer loses three days, rain on two
        r = random.Random(seed)
        counts = {}
        for s in scenes:
            for n in s["cast"]:
                counts[n] = counts.get(n, 0) + 1
        lead = max(counts, key=counts.get)
        used = sorted(set(plan.values()))
        gone = [dates[d].isoformat() for d in used[3:6]]
        rain = {dates[d].isoformat(): 0.6 for d in used[7:9]}
        near, _, _ = e.schedule(scenes, dates, world.RATES, world.FEES, {lead: gone}, rain, previous=plan, hint=None, seconds=10)
        fresh, _, _ = e.schedule(scenes, dates, world.RATES, world.FEES, {lead: gone}, rain, hint=None, seconds=10)
        assert not e.violations(scenes, near, dates, {lead: gone}) and not e.violations(scenes, fresh, dates, {lead: gone})
        moved = lambda q: sum(plan[k] != q[k] for k in plan)      # noqa: E731
        must = sum(1 for s in scenes if dates[plan[s["number"]]].isoformat() in gone and lead in s["cast"])
        rows.append((seed, a, b, status, bound, must, moved(near), moved(fresh), e.cost(scenes, near, dates, world.RATES, world.FEES, rain)["total"], e.cost(scenes, fresh, dates, world.RATES, world.FEES, rain)["total"]))
        r.random()
    n = p["scenes"]
    money = lambda v: f"${v / 1e6:.2f}M"      # noqa: E731
    lines = ["# Evaluation", "",
             f"Generated by `python -m fp.evaluate` on {len(SEEDS)} generated screenplays (seeds {SEEDS[0]} to {SEEDS[-1]}; 85 scenes each) that the demo and the tests never use.",
             "The screenplays are assembled from sentence banks in correct standard format, and all costs are assumed rates. Read these as a check that the parser and the solver work, not as real production figures.", "",
             "## 1. Breakdown", "",
             f"{n} scenes. A scene's cast is right only if it lists exactly the performers on set.", "",
             "| | Scenes with exactly the right cast | Headings read correctly | Page count right |", "|---|---|---|---|",
             f"| Parser: cues except voice-over, plus known names in action lines | {p['cast']} of {n} | {p['heading']} of {n} | {p['pages']} of {n} |", f"| Baseline: every character cue in the scene | {p['naive']} of {n} | | |", "",
             "The baseline calls performers who are only heard in voice-over and misses those who are on set without a line. Perfect scores here reflect a perfectly formatted script; real drafts have typos, dual dialogue and revision marks.", "",
             "## 2. Schedule cost", "",
             "Twelve seconds of solver time per screenplay, against shooting in script order (each scene on the first day where it fits every rule). Both satisfy every rule; the checker is separate code from the solver.", "",
             "| Screenplay | Script order | Solver | Saving | Shoot days | Solver status | Proven lower bound |", "|---|---|---|---|---|---|---|"]
    lines += [f"| {seed} | {money(b['total'])} | {money(a['total'])} | {1 - a['total'] / b['total']:.0%} | {b['shoot_days']} to {a['shoot_days']} | {status.lower()} | {money(bound)} |" for seed, a, b, status, bound, *_ in rows]
    lines += ["", "No schedule is proven optimal: the gap between the solver's answer and its lower bound is wide, which is normal for this kind of model in seconds. The comparison with script order is the meaningful one.",
              "The saving comes from fewer shoot days (crew cost), from keeping each performer's days together (they are paid from first day to last), and from fewer location days.", "",
              "## 3. Re-planning after a disruption", "",
              "The busiest performer loses three of their scheduled days and rain is forecast on two more. Re-solved two ways, ten seconds each:", "",
              "| Screenplay | Scenes that had to move | Moved, staying close to the plan | Moved, solving from scratch | Cost, staying close | Cost, from scratch |", "|---|---|---|---|---|---|"]
    lines += [f"| {seed} | {must} | {near} | {fresh} | {money(cn)} | {money(cf)} |" for seed, _, _, _, _, must, near, fresh, cn, cf in rows]
    lines += ["", "Staying close moves far fewer scenes than a fresh solve, which reshuffles most of the film. It still moves more than the minimum, because a moved scene usually displaces another."]
    out = pathlib.Path(__file__).resolve().parent.parent / "docs" / "evaluation.md"
    out.write_text("\n".join(lines) + "\n")
    print(out.read_text())


if __name__ == "__main__":
    main()
